### PR TITLE
Update title color ~ blue

### PR DESCRIPTION
**Pull request by LatinainTech**
before: 
Screenshot 2023-09-02 at 4 39 33 PM

after: 

Screenshot 2023-09-02 at 4 51 11 PM

### CODE REVIEW

**Comment by yoyoconnor** [comment]
We are not ohio state fans red is not our color. Because this class is part of the curriculum for the informatics degree of the refer me university. change color to blue.

**Comment by LatinainTech** [comment]
> We are not ohio state fans red is not our color. Because this class is part of the curriculum for the informatics degree of the refer me university. change color to blue.

updated to blue ! take a look

**Review by yoyoconnor — CHANGES_REQUESTED** [review]
Change to blue

**Review by yoyoconnor — COMMENTED** [review]
approved good job diana. also cs better than informatics, because showering=bad.

**Review by zero2sudo — APPROVED** [review]

**Pull request merged**
