### PR TITLE
Update quiz question 1 choices

### PR DESCRIPTION
**Pull request by anthonytang**
Update the first answer choice for the first question of the quiz

Before:
image

After:
image

### CODE REVIEW

**Comment by hyunbinjlee** [comment]
This is not true. Please change your quiz question 1 answer choice to UW > Rice

**Comment by anthonytang** [comment]
> This is not true. Please change your quiz question 1 answer choice to UW > Rice

Can we compromise that UW and Rice are both good?

**Comment by hyunbinjlee** [comment]
Yes, we can. Rice = UW

**Comment by zero2sudo** [comment]
Don’t forget to leave one correct answer related to Git!

________________________________

**Comment by anthonytang** [comment]
> Yes, we can. Rice = UW

Changed it. Does this look good to you?

> Yes, we can. Rice = UW

Changed it. Does this look good to you?

**Pull request merged**
