### PR TITLE
Add Additional Questions

### PR DESCRIPTION
**Pull request by LatinainTech**
before
Screenshot 2023-07-29 at 11 24 11 PM

after
Screenshot 2023-07-29 at 11 23 10 PM

### CODE REVIEW

**Comment by zero2sudo** [comment]
@LatinainTech please use the imperative tense for PR titles and commit messages

Added = past tense
Add = imperative

ex. Add new questions

**Comment by zero2sudo** [comment]
Awesome job with the new questions. Will approve your PR after we rebase (teaching that in lesson 3) and update PR title!

**Comment by LatinainTech** [comment]
Sounds good ! What else can I do before class ?

**Comment by LatinainTech** [comment]
Would you like me to do a PR before class or do I just wait till class ?

**Review by zero2sudo — APPROVED** [review]
LGTM

**Pull request merged**
